### ISSUE TITLE
How/where to change box-shadow for top bar

### ISSUE THREAD

**Issue by imanhodjaev** [LinxGem33/OSX-Arc-White#20]
Hi @LinxGem33 thank you for this cool theme! I am wondering how or where I can change the `box-shadow` properties for top bar (or global menu) shadows value is really big, so I wanted to change alpha and size of it.

<img width="562" alt="screen shot 2017-04-21 at 21 56 02" src="https://cloud.githubusercontent.com/assets/354868/25293967/61c1b56c-26dd-11e7-940e-a94e0948738c.png">

Thank you.

**Comment by LinxGem33** [comment]
@imanhodjaev 

appreciate the feed back, you can change the drop shadows by editing the `gnome-shell.css` file and by changing this section below you need to change the box shadow values also i don't recommend changing theme code unless you know what you are doing as this could introduce system instability if done wrong anyway code is below:

```css
/***********
 * Top Bar *
 ***********/
#panel {
    background-gradient-direction:none;
    background-color: rgba(255,255,255,0.75);
/*    background-color: rgba(46,51,56,0.9);
    border:1px solid rgba(200,200,200,.5);*/
    box-shadow: 0px 3px 3px 1px rgba(0,0,0,0.5);
    border: 0px solid rgba(90,105,111,0.5);
 /*	   box-shadow: 0px 0px 0px 1px rgba(0,0,0,0.15);*/
    border-top:0px;border-right:0px;border-left:0px;
    font-weight: bold;
height: 26px;}
```
kind regards
