### ISSUE TITLE
Blurry text on the taskbar

### ISSUE THREAD

**Issue by kimwnasptd** [LinxGem33/OSX-Arc-White#43]
![p1](https://user-images.githubusercontent.com/11134742/31400595-d80820a6-adf8-11e7-9731-a74579c47082.png) Blurry
![p2](https://user-images.githubusercontent.com/11134742/31400597-d84550d4-adf8-11e7-8309-c8e643ef5fa3.png) Clean

Just upgraded my GNOME from 3.24 to 3.26 (arch linux) and and my taskbar's text is blurry. But if I move a window on top, or if I maximize a window the text is correctly displayed. Any ideas why?

**Comment by snqlby** [comment]
the same problem, ty for you report

**Comment by snqlby** [comment]
@kimwnasptd try to add these lines to gnome-shell.css. This fix works great for me.
```CSS
/* Remove Shadows of Panel-buttons of GNOME 3.26 */
#panel .panel-button .system-status-icon,
#panel .panel-button .app-menu-icon > StIcon,
#panel .panel-button .popup-menu-arrow {
  text-shadow: none;
  icon-shadow: none;
}

 #panel .panel-button {
  text-shadow: none;
}

 #panel .panel-button:hover {
  text-shadow: none;
}

#panel .panel-button:hover .system-status-icon,
#panel .panel-button:hover .app-menu-icon > StIcon,
#panel .panel-button:hover .popup-menu-arrow {
  text-shadow: none;
  icon-shadow: none;
}

#panel.solid .panel-button {
  text-shadow: none;
}

#panel.solid .system-status-icon,
#panel.solid .app-menu-icon > StIcon,
#panel.solid .popup-menu-arrow {
  icon-shadow: none;
  text-shadow: none;
}
```
