### ISSUE TITLE
Is it possible to set no transparency?

### ISSUE THREAD

**Issue by matjaz132** [LinxGem33/OSX-Arc-White#9]
Is it possible to set no transparency?

**Comment by LinxGem33** [comment]
@matjaz132 

at the moment there isn't a non transparent version of the theme and other than changing the css it isn't really possible without overhauling the css.

kind regards

**Comment by Elbullazul** [comment]
@matjaz132 actually you can remove transparency. If you change the alpha settings in the following code, opacity should be 100%

```css

ooserDialog .dialog-vbox > .frame .button:active, GeditFileBrowserWidget .horizontal .button:active, GtkFileChooserDialog GtkFileChooserWidget > GtkActionBar > GtkRevealer > .action-bar.frame .button:checked,
  GtkFileChooserDialog .dialog-vbox > .frame .button:checked, GeditFileBrowserWidget .horizontal .button:checked {
    color: #ffffff;
    outline-color: rgba(255, 255, 255, 0.3);
    border-color: rgba(26, 28, 34, 0.35);
    background-color: #5294e2; }
  GtkFileChooserDialog GtkFileChooserWidget > GtkActionBar > GtkRevealer > .action-bar.frame .button:insensitive,
  GtkFileChooserDialog .dialog-vbox > .frame .button:insensitive, GeditFileBrowserWidget .horizontal .button:insensitive {
    color: #5d626e;
    border-color: rgba(26, 28, 34, 0.35);
    background-color: rgba(102, 109, 132, 0.2); }

GtkFileChooserDialog GtkFileChooserWidget > GtkActionBar > GtkRevealer > .action-bar.frame .entry,
GtkFileChooserDialog .dialog-vbox > .frame .entry {
  color: #BAC3CF;
  border-color: rgba(26, 28, 34, 0.35);
  background-image: linear-gradient(to bottom, rgba(102, 109, 132, 0.35));
  background-color: transparent; }
  GtkFileChooserDialog GtkFileChooserWidget > GtkActionBar > GtkRevealer > .action-bar.frame .image.entry,
  GtkFileChooserDialog .dialog-vbox > .frame .image.entry, GtkFileChooserDialog GtkFileChooserWidget > GtkActionBar > GtkRevealer > .action-bar.frame .image.entry:hover,
  GtkFileChooserDialog .dialog-vbox > .frame .image.entry:hover {
    color: inherit; }
  GtkFileChooserDialog GtkFileChooserWidget > GtkActionBar > GtkRevealer > .action-bar.frame .entry:focus,
  GtkFileChooserDialog .dialog-vbox > .frame .entry:focus {
    color: #ffffff;
    border-color: rgba(26, 28, 34, 0.35);
    background-image: linear-gradient(to bottom, #5294e2); }
  GtkFileChooserDialog GtkFileChooserWidget > GtkActionBar > GtkRevealer > .action-bar.frame .entry:insensitive,
  GtkFileChooserDialog .dialog-vbox > .frame .entry:insensitive {
    color: rgba(186, 195, 207, 0.55);
    background-image: linear-gradient(to bottom, rgba(102, 109, 132, 0.2)); }

GtkFileChooserDialog GtkPlacesSidebar.sidebar .overlay-indicator.scrollbar:not(.dragging):not(.hovering) .slider,
NautilusWindow GtkPlacesSidebar.sidebar .overlay-indicator.scrollbar:not(.dragging):not(.hovering) .slider, NemoWindow .sidebar .overlay-indicator.scrollbar:not(.dragging):not(.hovering) .slider,
MarlinViewWindow .sidebar .overlay-indicator.scrollbar:not(.dragging):not(.hovering) .slider, GeditFileBrowserWidget .overlay-indicator.scrollbar:not(.dragging):not(.hovering) .slider {
  background-color: #e7eaee;
  border: 1px solid rgba(0, 0, 0, 0.3); }

GtkFileChooserDialog GtkPlacesSidebar.sidebar .scrollbar .trough,
NautilusWindow GtkPlacesSidebar.sidebar .scrollbar .trough, NemoWindow .sidebar .scrollbar .trough, NemoWindow .source-list.sidebar.view .scrollbar .trough,
MarlinViewWindow .sidebar .scrollbar .trough,
MarlinViewWindow .source-list.sidebar.view .scrollbar .trough, GeditFileBrowserWidget .scrollbar .trough {
  background-color: rgba(0, 0, 0, 0.2);
  border: none; }

GtkFileChooserDialog GtkPlacesSidebar.sidebar .scrollbar .slider,
NautilusWindow GtkPlacesSidebar.sidebar .scrollbar .slider, NemoWindow .sidebar .scrollbar .slider, NemoWindow .source-list.sidebar.view .scrollbar .slider,
MarlinViewWindow .sidebar .scrollbar .slider,
MarlinViewWindow .source-list.sidebar.view .scrollbar .slider, GeditFileBrowserWidget .scrollbar .slider {
  background-color: rgba(231, 234, 238, 0.7); }
  GtkFileChooserDialog GtkPlacesSidebar.sidebar .scrollbar .slider:hover,
  NautilusWindow GtkPlacesSidebar.sidebar .scrollbar .slider:hover, NemoWindow .sidebar .scrollbar .slider:hover,
  MarlinViewWindow .sidebar .scrollbar .slider:hover, GeditFileBrowserWidget .scrollbar .slider:hover {
    background-color: #f6f7f9; }
  GtkFileChooserDialog GtkPlacesSidebar.sidebar .scrollbar .slider:prelight:active,
  NautilusWindow GtkPlacesSidebar.sidebar .scrollbar .slider:prelight:active, NemoWindow .sidebar .scrollbar .slider:prelight:active,
  MarlinViewWindow .sidebar .scrollbar .slider:prelight:active, GeditFileBrowserWidget .scrollbar .slider:prelight:active {
    background-color: #5294e2; }
  GtkFileChooserDialog GtkPlacesSidebar.sidebar .scrollbar .slider:insensitive,
  NautilusWindow GtkPlacesSidebar.sidebar .scrollbar .slider:insensitive, NemoWindow .sidebar .scrollbar .slider:insensitive,
  MarlinViewWindow .sidebar .scrollbar .slider:insensitive, GeditFileBrowserWidget .scrollbar .slider:insensitive {
    background-color: transparent; }

```
